### ISSUE TITLE
org service v2 and transition for SaaS customers

### ISSUE THREAD

**Issue by okundzich** [moderneinc/moderne-organizations#76]
TBD - we need to discuss this. We need to merge old APIs and new APIs as necessary and enable transition in the SaaS supporting both for a time. 

how do we migrate SaaS customers to org service v2? What APIs do we need to add to org service v2? How do we enable it in the template? Who’s using commits and user organizations in our SaaS customer base?

Looking at this document, I suggest we switch phase 4 and 5 around and then implement `mod org devcenter show` - this is not the right command btw, just we need something like this in both DX and SaaS. 

https://docs.google.com/document/d/18mtebL5P2U8RCa8JYRbmkJQrZQGwFjhH8G-6VEg1XMQ/edit

[Slack Message](https://moderneinc.slack.com/archives/C01S4M53THT/p1716331619028129?thread_ts=1716331609.447769&cid=C01S4M53THT)
```[tasklist]
### Tasks
- [x] remove deprecated query from v2
- [x] update template to use v2
- [x] achive temporary v2 template
- [x] add moderne/repos.csv
- [x] add qbuzz/repos.csv
- [x] use public/repos.csv + jl/repos.csv in public-mass-ingest
- [x] use moderne/repos.csv in moderne-mass-ingest
- [x] generate public/repos.csv inside organizations-multitenant
- [x] generate moderne/repos.csv inside organizations-multitenant
- [x] Secure organizations-multitenant
- [ ] change RE to not use `organizations(repositoryInput)` if `Organization` type has `repositories` field
- [ ] remove `organizations(repositoryInput)` on some date.yInput)` once all customers migrated.
```

**Comment by pstreef** [comment]
using repos.csv inside mass-ingest:

https://github.com/moderneinc/public-mass-ingest/pull/10
https://github.com/moderneinc/moderne-mass-ingest/pull/3

**Comment by pstreef** [comment]
Draft PR: https://github.com/moderneinc/moderne-organizations-multitenant/pull/129

**Comment by pstreef** [comment]
original template is now updated to v2. Temporary template is archived. Documentation updated.

**Comment by pstreef** [comment]
PR https://github.com/moderneinc/moderne-organizations-multitenant/pull/129 is now pending only on removing the public LB.

**Comment by pstreef** [comment]
I think we can park `generate public/repos.csv inside organizations-multitenant` for now. We will probably do this only a few times a year so automating it is a probably a lower priority.

**Comment by pstreef** [comment]
PR to disable v1 query if v2 is available. Should be merged after  https://github.com/moderneinc/moderne-organizations-multitenant/pull/129

https://github.com/moderneinc/moderne-recipe-execution/pull/925
